FROM centos:centos7 AS base-dependencies
LABEL author="James Cherry"
LABEL maintainer="James Cherry <cherry@parallaxsw.com>"

# CentOS 7 mirrors are gone. vault.centos.org HTTP now 301s to HTTPS, which
# yum cannot follow, so use kernel.org's HTTP vault instead. Re-apply after
# packages that overwrite or add .repo files (centos-release, SCLo, EPEL).
RUN sed -i \
        -e 's/^mirrorlist=/#mirrorlist=/' \
        -e 's/^#[[:space:]]*baseurl=/baseurl=/' \
        -e 's|mirror.centos.org/centos|archive.kernel.org/centos-vault|g' \
        /etc/yum.repos.d/*.repo \
    && yum update -y \
    && yum install -y centos-release-scl epel-release
RUN sed -i \
        -e 's/^mirrorlist=/#mirrorlist=/' \
        -e 's/^#[[:space:]]*baseurl=/baseurl=/' \
        -e 's|mirror.centos.org/centos|archive.kernel.org/centos-vault|g' \
        /etc/yum.repos.d/*.repo \
    && yum install -y devtoolset-11 git wget cmake3 make eigen3-devel \
        tcl swig3 flex zlib-devel valgrind \
    && yum clean -y all

RUN ln -sf /usr/bin/cmake3 /usr/bin/cmake

# Download Bison
RUN wget https://mirrors.kernel.org/gnu/bison/bison-3.8.2.tar.gz && \
    tar -xvf bison-3.8.2.tar.gz && \
    rm bison-3.8.2.tar.gz

# Build Bison
RUN source /opt/rh/devtoolset-11/enable && \
    cd bison-3.8.2 && \
    ./configure && \
    make -j`nproc` && \
    make install

# Download CUDD
RUN wget https://raw.githubusercontent.com/davidkebo/cudd/main/cudd_versions/cudd-3.0.0.tar.gz && \
    tar -xvf cudd-3.0.0.tar.gz && \
    rm cudd-3.0.0.tar.gz

# Build CUDD
RUN source /opt/rh/devtoolset-11/enable && \
    cd cudd-3.0.0 && \
    mkdir ../cudd && \
    ./configure && \
    make -j`nproc` && \
    make install

# Download TCL
RUN wget https://github.com/tcltk/tcl/archive/refs/tags/core-8-6-16.tar.gz -O tcl8.6.16-src.tar.gz && \
    mkdir -p tcl8.6.16 && \
    tar -xvf tcl8.6.16-src.tar.gz -C tcl8.6.16 --strip-components=1 && \
    rm tcl8.6.16-src.tar.gz

# Build TCL
RUN source /opt/rh/devtoolset-11/enable && \
    cd tcl8.6.16 && \
    ./unix/configure && \
    make -j`nproc` && \
    make install

# Download and build fmt
# Re-apply the vault rewrite in case a prior install dropped new .repo files.
RUN sed -i \
        -e 's/^mirrorlist=/#mirrorlist=/' \
        -e 's/^#[[:space:]]*baseurl=/baseurl=/' \
        -e 's|mirror.centos.org/centos|archive.kernel.org/centos-vault|g' \
        /etc/yum.repos.d/*.repo && \
    yum install -y ca-certificates git && \
    update-ca-trust force-enable
# clone fmt compatible version (10.2.1)
RUN git config --global http.sslVerify false && \
    git clone --depth 1 --branch 10.2.1 https://github.com/fmtlib/fmt.git /tmp/fmt
RUN source /opt/rh/devtoolset-11/enable && \
    cd /tmp/fmt && \
    mkdir build && cd build && \
    cmake3 .. \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DFMT_TEST=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DFMT_DOC=OFF && \
    make -j$(nproc) && \
    make install
RUN rm -rf /tmp/fmt

################################################################

FROM base-dependencies AS builder

COPY . /OpenSTA
WORKDIR /OpenSTA

# Build
RUN rm -rf build && mkdir build
RUN source /opt/rh/devtoolset-11/enable && \
    cd build && \
    cmake .. && \
    # LTO fails with -j
    make

# Run sta on entry
ENTRYPOINT ["/OpenSTA/build/sta"]
